import type { Metadata } from 'next';

import { useConfigStore } from '@/app/store/config';
import '@/app/globals.css';
import StoreInitializer from '@/app/StoreInitializer';
import Header from '@/app/components/Header';

export const metadata: Metadata = {
  title: 'HypeBold',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const getConfig = await fetch(`${process.env.NEXT_PUBLIC_API}/config`, {
    next: { revalidate: 3600, tags: ['config'] },
  });
  const config = await getConfig.json();
  useConfigStore.setState({ config: config.data });

  return (
    <html lang='en'>
      <body>
        <StoreInitializer config={config.data} />
        <Header />
        {children}
      </body>
    </html>
  );
}
